# Site settings
title: vandeweerdt.com
email:
  nope
description: > # this means to ignore newlines until the next tag
  I might use this some day...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bartvandeweerdt.github.io" # the base hostname & protocol for your site
twitter_username: bartvandeweerdt
github_username:  bartvandeweerdt

# Build settings
markdown: kramdown
